### PR TITLE
Feat/api versioning

### PR DESCRIPTION
**Pull request by NaufalMuh11**
## Description
Create API versioning in `routes/api/v1/api.php` with prefix `v1`. Also create a `UserController` and `ApiV1Routes.php` for testing

## Types  Of Change

- [ ] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by nugrahaAdhitama** [comment]
Are you using `resources` to standardize the API response?

**Comment by NaufalMuh11** [comment]
> Are you using `resources` to standardize the API response? @NaufalMuh11

no sir

**Comment by nugrahaAdhitama** [comment]
Please create `resources` for the existing controller first so that all future API responses can be standardized through `resources`. The rest of your code is well-written; you just need to make this minor revision. @NaufalMuh11

**Review by KronosDP — APPROVED** [review]
good

**Pull request merged**
